### ISSUE TITLE
您好，我是一名硕士生，我对这篇论文很感兴趣，能一起沟通一下吗，谢谢！

### ISSUE THREAD

**Issue by HNing109** [zhouziqunzzq/GP-MANN#1]
您好，我是一名硕士生，我对这篇论文很感兴趣，能一起沟通一下吗，谢谢！

**Comment by zhouziqunzzq** [comment]
您好，感谢您的关注，我的邮箱：zhouziqun AT cool2645.com  (AT = @)，欢迎交流~
